[tool.poetry]
name = "storybook-fun-factory"
version = "0.1.0"
description = "A recursive sandbox for testing assistant delegation systems in Storybook."
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.packages]
packages = [
    { include = "storybook_fun_factory", from = "src" }
]
